/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : bigint,
  'status' : ApplicationStatus,
  'requirementId' : bigint,
  'playerId' : Principal,
  'createdAt' : bigint,
  'roleApplied' : Role,
  'teamId' : Principal,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface ApplicationWithPlayerInfo {
  'id' : bigint,
  'status' : ApplicationStatus,
  'requirementId' : bigint,
  'playerUsername' : string,
  'playerId' : Principal,
  'createdAt' : bigint,
  'roleApplied' : Role,
  'playerReadinessScore' : bigint,
  'teamId' : Principal,
}
export interface Endorsement {
  'id' : bigint,
  'playerId' : Principal,
  'createdAt' : bigint,
  'endorsementType' : EndorsementType,
  'endorserId' : Principal,
}
export interface EndorsementSummary {
  'customEndorsements' : Array<[{ 'name' : string }, { 'count' : bigint }]>,
  'consistencyCount' : bigint,
  'reliableCommsCount' : bigint,
  'scrimPartnerCount' : bigint,
  'punctualCount' : bigint,
}
export type EndorsementType = { 'custom' : string } |
  { 'punctual' : null } |
  { 'scrimPartner' : null } |
  { 'consistency' : null } |
  { 'reliableComms' : null };
export type ExternalBlob = Uint8Array;
export interface Feedback {
  'id' : bigint,
  'userId' : Principal,
  'message' : string,
  'timestamp' : bigint,
}
export type Game = { 'freeFire' : null } |
  { 'other' : string } |
  { 'bgmi' : null } |
  { 'codm' : null };
export interface HiringRequirement {
  'id' : bigint,
  'game' : Game,
  'createdAt' : bigint,
  'role' : Role,
  'minReadinessScore' : bigint,
  'skillLevel' : Level,
  'teamId' : Principal,
  'requirements' : string,
}
export type Level = { 'grinder' : null } |
  { 'casual' : null };
export interface Post {
  'id' : bigint,
  'clip' : [] | [ExternalBlob],
  'userId' : Principal,
  'improvementText' : string,
  'createdAt' : bigint,
}
export interface ReadinessMetrics {
  'readinessRequirement' : bigint,
  'globalReadinessScore' : bigint,
}
export type Role = { 'attacker' : null } |
  { 'other' : string } |
  { 'support' : null } |
  { 'tank' : null } |
  { 'sniper' : null };
export interface SystemHiringRequirement {
  'id' : bigint,
  'teamName' : string,
  'contactInfo' : string,
  'game' : Game,
  'createdAt' : bigint,
  'role' : Role,
  'minReadinessScore' : bigint,
  'skillLevel' : Level,
  'teamId' : Principal,
  'requirements' : string,
}
export interface SystemHiringRequirementSearchFilters {
  'game' : [] | [Game],
  'role' : [] | [Role],
  'minReadinessScore' : [] | [bigint],
  'returnedFields' : [] | [Array<string>],
  'skillLevel' : [] | [Level],
  'searchQuery' : [] | [string],
}
export interface TalentSearchFilters {
  'hasClipOnly' : boolean,
  'game' : [] | [Game],
  'role' : [] | [Role],
  'minReadinessScore' : [] | [bigint],
  'level' : [] | [Level],
  'openToTeamOnly' : boolean,
  'searchQuery' : [] | [string],
}
export interface TeamProfile {
  'id' : Principal,
  'userType' : UserType,
  'teamName' : string,
  'contactInfo' : string,
  'gamesRecruiting' : Array<Game>,
  'description' : string,
  'requirements' : string,
}
export interface User {
  'id' : Principal,
  'userType' : [] | [UserType],
  'name' : string,
  'email' : string,
  'avatar' : string,
}
export interface UserProfile {
  'id' : Principal,
  'userType' : UserType,
  'username' : string,
  'game' : Game,
  'role' : Role,
  'level' : Level,
  'readinessRequirement' : bigint,
  'globalReadinessScore' : bigint,
  'openToTeam' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserType = { 'player' : null } |
  { 'team' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyToRequirement' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createHiringRequirement' : ActorMethod<
    [Game, Role, Level, bigint, string],
    undefined
  >,
  'createOrUpdateProfile' : ActorMethod<
    [UserType, Game, Role, Level, boolean, bigint, string],
    undefined
  >,
  'createOrUpdateTeamProfile' : ActorMethod<
    [string, Array<Game>, string, string, string],
    undefined
  >,
  'createPost' : ActorMethod<[string, [] | [ExternalBlob]], undefined>,
  'deleteEndorsement' : ActorMethod<[bigint], EndorsementSummary>,
  'getAllEndorsements' : ActorMethod<[], Array<Endorsement>>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAllHiringRequirements' : ActorMethod<[], Array<HiringRequirement>>,
  'getApplicationsForTeam' : ActorMethod<[], Array<ApplicationWithPlayerInfo>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentUser' : ActorMethod<[], User>,
  'getFeed' : ActorMethod<[], Array<Post>>,
  'getPlayerApplications' : ActorMethod<[], Array<Application>>,
  'getPlayerEndorsementSummary' : ActorMethod<[Principal], EndorsementSummary>,
  'getPlayerEndorsements' : ActorMethod<[Principal], Array<Endorsement>>,
  'getReadinessMetrics' : ActorMethod<[[] | [Principal]], ReadinessMetrics>,
  'getTeamHiringRequirements' : ActorMethod<
    [[] | [Principal]],
    Array<HiringRequirement>
  >,
  'getTeamProfile' : ActorMethod<[[] | [Principal]], [] | [TeamProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTimeline' : ActorMethod<[Principal], Array<Post>>,
  'initializeUser' : ActorMethod<[string, string, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchAllHiringRequirementsForPlayers' : ActorMethod<
    [SystemHiringRequirementSearchFilters],
    Array<SystemHiringRequirement>
  >,
  'searchTalent' : ActorMethod<[TalentSearchFilters], Array<UserProfile>>,
  'setUserType' : ActorMethod<[UserType], undefined>,
  'submitEndorsement' : ActorMethod<
    [Principal, EndorsementType],
    EndorsementSummary
  >,
  'submitFeedback' : ActorMethod<[string], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    undefined
  >,
  'updateReadinessRequirement' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];