/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Game = IDL.Variant({
  'freeFire' : IDL.Null,
  'other' : IDL.Text,
  'bgmi' : IDL.Null,
  'codm' : IDL.Null,
});
export const Role = IDL.Variant({
  'attacker' : IDL.Null,
  'other' : IDL.Text,
  'support' : IDL.Null,
  'tank' : IDL.Null,
  'sniper' : IDL.Null,
});
export const Level = IDL.Variant({ 'grinder' : IDL.Null, 'casual' : IDL.Null });
export const UserType = IDL.Variant({ 'player' : IDL.Null, 'team' : IDL.Null });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const EndorsementSummary = IDL.Record({
  'customEndorsements' : IDL.Vec(
    IDL.Tuple(
      IDL.Record({ 'name' : IDL.Text }),
      IDL.Record({ 'count' : IDL.Nat }),
    )
  ),
  'consistencyCount' : IDL.Nat,
  'reliableCommsCount' : IDL.Nat,
  'scrimPartnerCount' : IDL.Nat,
  'punctualCount' : IDL.Nat,
});
export const EndorsementType = IDL.Variant({
  'custom' : IDL.Text,
  'punctual' : IDL.Null,
  'scrimPartner' : IDL.Null,
  'consistency' : IDL.Null,
  'reliableComms' : IDL.Null,
});
export const Endorsement = IDL.Record({
  'id' : IDL.Nat,
  'playerId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'endorsementType' : EndorsementType,
  'endorserId' : IDL.Principal,
});
export const Feedback = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const HiringRequirement = IDL.Record({
  'id' : IDL.Nat,
  'game' : Game,
  'createdAt' : IDL.Int,
  'role' : Role,
  'minReadinessScore' : IDL.Int,
  'skillLevel' : Level,
  'teamId' : IDL.Principal,
  'requirements' : IDL.Text,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const ApplicationWithPlayerInfo = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'requirementId' : IDL.Nat,
  'playerUsername' : IDL.Text,
  'playerId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'roleApplied' : Role,
  'playerReadinessScore' : IDL.Int,
  'teamId' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'userType' : UserType,
  'username' : IDL.Text,
  'game' : Game,
  'role' : Role,
  'level' : Level,
  'readinessRequirement' : IDL.Int,
  'globalReadinessScore' : IDL.Int,
  'openToTeam' : IDL.Bool,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'userType' : IDL.Opt(UserType),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'avatar' : IDL.Text,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'clip' : IDL.Opt(ExternalBlob),
  'userId' : IDL.Principal,
  'improvementText' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const Application = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'requirementId' : IDL.Nat,
  'playerId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'roleApplied' : Role,
  'teamId' : IDL.Principal,
});
export const ReadinessMetrics = IDL.Record({
  'readinessRequirement' : IDL.Int,
  'globalReadinessScore' : IDL.Int,
});
export const TeamProfile = IDL.Record({
  'id' : IDL.Principal,
  'userType' : UserType,
  'teamName' : IDL.Text,
  'contactInfo' : IDL.Text,
  'gamesRecruiting' : IDL.Vec(Game),
  'description' : IDL.Text,
  'requirements' : IDL.Text,
});
export const SystemHiringRequirementSearchFilters = IDL.Record({
  'game' : IDL.Opt(Game),
  'role' : IDL.Opt(Role),
  'minReadinessScore' : IDL.Opt(IDL.Int),
  'returnedFields' : IDL.Opt(IDL.Vec(IDL.Text)),
  'skillLevel' : IDL.Opt(Level),
  'searchQuery' : IDL.Opt(IDL.Text),
});
export const SystemHiringRequirement = IDL.Record({
  'id' : IDL.Nat,
  'teamName' : IDL.Text,
  'contactInfo' : IDL.Text,
  'game' : Game,
  'createdAt' : IDL.Int,
  'role' : Role,
  'minReadinessScore' : IDL.Int,
  'skillLevel' : Level,
  'teamId' : IDL.Principal,
  'requirements' : IDL.Text,
});
export const TalentSearchFilters = IDL.Record({
  'hasClipOnly' : IDL.Bool,
  'game' : IDL.Opt(Game),
  'role' : IDL.Opt(Role),
  'minReadinessScore' : IDL.Opt(IDL.Int),
  'level' : IDL.Opt(Level),
  'openToTeamOnly' : IDL.Bool,
  'searchQuery' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyToRequirement' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createHiringRequirement' : IDL.Func(
      [Game, Role, Level, IDL.Int, IDL.Text],
      [],
      [],
    ),
  'createOrUpdateProfile' : IDL.Func(
      [UserType, Game, Role, Level, IDL.Bool, IDL.Int, IDL.Text],
      [],
      [],
    ),
  'createOrUpdateTeamProfile' : IDL.Func(
      [IDL.Text, IDL.Vec(Game), IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createPost' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'deleteEndorsement' : IDL.Func([IDL.Nat], [EndorsementSummary], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'editPost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllEndorsements' : IDL.Func([], [IDL.Vec(Endorsement)], ['query']),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllHiringRequirements' : IDL.Func(
      [],
      [IDL.Vec(HiringRequirement)],
      ['query'],
    ),
  'getApplicationsForTeam' : IDL.Func(
      [],
      [IDL.Vec(ApplicationWithPlayerInfo)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentUser' : IDL.Func([], [User], ['query']),
  'getFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPlayerApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getPlayerEndorsementSummary' : IDL.Func(
      [IDL.Principal],
      [EndorsementSummary],
      ['query'],
    ),
  'getPlayerEndorsements' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Endorsement)],
      ['query'],
    ),
  'getReadinessMetrics' : IDL.Func(
      [IDL.Opt(IDL.Principal)],
      [ReadinessMetrics],
      ['query'],
    ),
  'getTeamHiringRequirements' : IDL.Func(
      [IDL.Opt(IDL.Principal)],
      [IDL.Vec(HiringRequirement)],
      ['query'],
    ),
  'getTeamProfile' : IDL.Func(
      [IDL.Opt(IDL.Principal)],
      [IDL.Opt(TeamProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTimeline' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'initializeUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchAllHiringRequirementsForPlayers' : IDL.Func(
      [SystemHiringRequirementSearchFilters],
      [IDL.Vec(SystemHiringRequirement)],
      ['query'],
    ),
  'searchTalent' : IDL.Func(
      [TalentSearchFilters],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'setUserType' : IDL.Func([UserType], [], []),
  'submitEndorsement' : IDL.Func(
      [IDL.Principal, EndorsementType],
      [EndorsementSummary],
      [],
    ),
  'submitFeedback' : IDL.Func([IDL.Text], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  'updateReadinessRequirement' : IDL.Func([IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Game = IDL.Variant({
    'freeFire' : IDL.Null,
    'other' : IDL.Text,
    'bgmi' : IDL.Null,
    'codm' : IDL.Null,
  });
  const Role = IDL.Variant({
    'attacker' : IDL.Null,
    'other' : IDL.Text,
    'support' : IDL.Null,
    'tank' : IDL.Null,
    'sniper' : IDL.Null,
  });
  const Level = IDL.Variant({ 'grinder' : IDL.Null, 'casual' : IDL.Null });
  const UserType = IDL.Variant({ 'player' : IDL.Null, 'team' : IDL.Null });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const EndorsementSummary = IDL.Record({
    'customEndorsements' : IDL.Vec(
      IDL.Tuple(
        IDL.Record({ 'name' : IDL.Text }),
        IDL.Record({ 'count' : IDL.Nat }),
      )
    ),
    'consistencyCount' : IDL.Nat,
    'reliableCommsCount' : IDL.Nat,
    'scrimPartnerCount' : IDL.Nat,
    'punctualCount' : IDL.Nat,
  });
  const EndorsementType = IDL.Variant({
    'custom' : IDL.Text,
    'punctual' : IDL.Null,
    'scrimPartner' : IDL.Null,
    'consistency' : IDL.Null,
    'reliableComms' : IDL.Null,
  });
  const Endorsement = IDL.Record({
    'id' : IDL.Nat,
    'playerId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'endorsementType' : EndorsementType,
    'endorserId' : IDL.Principal,
  });
  const Feedback = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const HiringRequirement = IDL.Record({
    'id' : IDL.Nat,
    'game' : Game,
    'createdAt' : IDL.Int,
    'role' : Role,
    'minReadinessScore' : IDL.Int,
    'skillLevel' : Level,
    'teamId' : IDL.Principal,
    'requirements' : IDL.Text,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const ApplicationWithPlayerInfo = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'requirementId' : IDL.Nat,
    'playerUsername' : IDL.Text,
    'playerId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'roleApplied' : Role,
    'playerReadinessScore' : IDL.Int,
    'teamId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'userType' : UserType,
    'username' : IDL.Text,
    'game' : Game,
    'role' : Role,
    'level' : Level,
    'readinessRequirement' : IDL.Int,
    'globalReadinessScore' : IDL.Int,
    'openToTeam' : IDL.Bool,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'userType' : IDL.Opt(UserType),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'avatar' : IDL.Text,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'clip' : IDL.Opt(ExternalBlob),
    'userId' : IDL.Principal,
    'improvementText' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'requirementId' : IDL.Nat,
    'playerId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'roleApplied' : Role,
    'teamId' : IDL.Principal,
  });
  const ReadinessMetrics = IDL.Record({
    'readinessRequirement' : IDL.Int,
    'globalReadinessScore' : IDL.Int,
  });
  const TeamProfile = IDL.Record({
    'id' : IDL.Principal,
    'userType' : UserType,
    'teamName' : IDL.Text,
    'contactInfo' : IDL.Text,
    'gamesRecruiting' : IDL.Vec(Game),
    'description' : IDL.Text,
    'requirements' : IDL.Text,
  });
  const SystemHiringRequirementSearchFilters = IDL.Record({
    'game' : IDL.Opt(Game),
    'role' : IDL.Opt(Role),
    'minReadinessScore' : IDL.Opt(IDL.Int),
    'returnedFields' : IDL.Opt(IDL.Vec(IDL.Text)),
    'skillLevel' : IDL.Opt(Level),
    'searchQuery' : IDL.Opt(IDL.Text),
  });
  const SystemHiringRequirement = IDL.Record({
    'id' : IDL.Nat,
    'teamName' : IDL.Text,
    'contactInfo' : IDL.Text,
    'game' : Game,
    'createdAt' : IDL.Int,
    'role' : Role,
    'minReadinessScore' : IDL.Int,
    'skillLevel' : Level,
    'teamId' : IDL.Principal,
    'requirements' : IDL.Text,
  });
  const TalentSearchFilters = IDL.Record({
    'hasClipOnly' : IDL.Bool,
    'game' : IDL.Opt(Game),
    'role' : IDL.Opt(Role),
    'minReadinessScore' : IDL.Opt(IDL.Int),
    'level' : IDL.Opt(Level),
    'openToTeamOnly' : IDL.Bool,
    'searchQuery' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyToRequirement' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createHiringRequirement' : IDL.Func(
        [Game, Role, Level, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'createOrUpdateProfile' : IDL.Func(
        [UserType, Game, Role, Level, IDL.Bool, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'createOrUpdateTeamProfile' : IDL.Func(
        [IDL.Text, IDL.Vec(Game), IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createPost' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'deleteEndorsement' : IDL.Func([IDL.Nat], [EndorsementSummary], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'editPost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllEndorsements' : IDL.Func([], [IDL.Vec(Endorsement)], ['query']),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllHiringRequirements' : IDL.Func(
        [],
        [IDL.Vec(HiringRequirement)],
        ['query'],
      ),
    'getApplicationsForTeam' : IDL.Func(
        [],
        [IDL.Vec(ApplicationWithPlayerInfo)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentUser' : IDL.Func([], [User], ['query']),
    'getFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPlayerApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getPlayerEndorsementSummary' : IDL.Func(
        [IDL.Principal],
        [EndorsementSummary],
        ['query'],
      ),
    'getPlayerEndorsements' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Endorsement)],
        ['query'],
      ),
    'getReadinessMetrics' : IDL.Func(
        [IDL.Opt(IDL.Principal)],
        [ReadinessMetrics],
        ['query'],
      ),
    'getTeamHiringRequirements' : IDL.Func(
        [IDL.Opt(IDL.Principal)],
        [IDL.Vec(HiringRequirement)],
        ['query'],
      ),
    'getTeamProfile' : IDL.Func(
        [IDL.Opt(IDL.Principal)],
        [IDL.Opt(TeamProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTimeline' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'initializeUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchAllHiringRequirementsForPlayers' : IDL.Func(
        [SystemHiringRequirementSearchFilters],
        [IDL.Vec(SystemHiringRequirement)],
        ['query'],
      ),
    'searchTalent' : IDL.Func(
        [TalentSearchFilters],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'setUserType' : IDL.Func([UserType], [], []),
    'submitEndorsement' : IDL.Func(
        [IDL.Principal, EndorsementType],
        [EndorsementSummary],
        [],
      ),
    'submitFeedback' : IDL.Func([IDL.Text], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
    'updateReadinessRequirement' : IDL.Func([IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };