/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HiringRequirement {
    id: bigint;
    game: Game;
    createdAt: bigint;
    role: Role;
    minReadinessScore: bigint;
    skillLevel: Level;
    teamId: Principal;
    requirements: string;
}
export type Game = {
    __kind__: "freeFire";
    freeFire: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "bgmi";
    bgmi: null;
} | {
    __kind__: "codm";
    codm: null;
};
export interface ReadinessMetrics {
    readinessRequirement: bigint;
    globalReadinessScore: bigint;
}
export interface User {
    id: Principal;
    userType?: UserType;
    name: string;
    email: string;
    avatar: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface SystemHiringRequirementSearchFilters {
    game?: Game;
    role?: Role;
    minReadinessScore?: bigint;
    returnedFields?: Array<string>;
    skillLevel?: Level;
    searchQuery?: string;
}
export interface Feedback {
    id: bigint;
    userId: Principal;
    message: string;
    timestamp: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TalentSearchFilters {
    hasClipOnly: boolean;
    game?: Game;
    role?: Role;
    minReadinessScore?: bigint;
    level?: Level;
    openToTeamOnly: boolean;
    searchQuery?: string;
}
export type EndorsementType = {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "punctual";
    punctual: null;
} | {
    __kind__: "scrimPartner";
    scrimPartner: null;
} | {
    __kind__: "consistency";
    consistency: null;
} | {
    __kind__: "reliableComms";
    reliableComms: null;
};
export type Role = {
    __kind__: "attacker";
    attacker: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "support";
    support: null;
} | {
    __kind__: "tank";
    tank: null;
} | {
    __kind__: "sniper";
    sniper: null;
};
export interface Endorsement {
    id: bigint;
    playerId: Principal;
    createdAt: bigint;
    endorsementType: EndorsementType;
    endorserId: Principal;
}
export interface TeamProfile {
    id: Principal;
    userType: UserType;
    teamName: string;
    contactInfo: string;
    gamesRecruiting: Array<Game>;
    description: string;
    requirements: string;
}
export interface Post {
    id: bigint;
    clip?: ExternalBlob;
    userId: Principal;
    improvementText: string;
    createdAt: bigint;
}
export interface EndorsementSummary {
    customEndorsements: Array<[{
            name: string;
        }, {
            count: bigint;
        }]>;
    consistencyCount: bigint;
    reliableCommsCount: bigint;
    scrimPartnerCount: bigint;
    punctualCount: bigint;
}
export interface SystemHiringRequirement {
    id: bigint;
    teamName: string;
    contactInfo: string;
    game: Game;
    createdAt: bigint;
    role: Role;
    minReadinessScore: bigint;
    skillLevel: Level;
    teamId: Principal;
    requirements: string;
}
export interface UserProfile {
    id: Principal;
    userType: UserType;
    username: string;
    game: Game;
    role: Role;
    level: Level;
    readinessRequirement: bigint;
    globalReadinessScore: bigint;
    openToTeam: boolean;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Level {
    grinder = "grinder",
    casual = "casual"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserType {
    player = "player",
    team = "team"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createHiringRequirement(game: Game, role: Role, skillLevel: Level, minReadinessScore: bigint, requirements: string): Promise<void>;
    createOrUpdateProfile(userType: UserType, game: Game, role: Role, level: Level, openToTeam: boolean, readinessRequirement: bigint, username: string): Promise<void>;
    createOrUpdateTeamProfile(teamName: string, gamesRecruiting: Array<Game>, description: string, requirements: string, contactInfo: string): Promise<void>;
    createPost(improvementText: string, clip: ExternalBlob | null): Promise<void>;
    deleteEndorsement(endorsementId: bigint): Promise<EndorsementSummary>;
    getAllEndorsements(): Promise<Array<Endorsement>>;
    getAllFeedback(): Promise<Array<Feedback>>;
    getAllHiringRequirements(): Promise<Array<HiringRequirement>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentUser(): Promise<User>;
    getFeed(): Promise<Array<Post>>;
    getPlayerEndorsementSummary(playerId: Principal): Promise<EndorsementSummary>;
    getPlayerEndorsements(playerId: Principal): Promise<Array<Endorsement>>;
    getReadinessMetrics(userId: Principal | null): Promise<ReadinessMetrics>;
    getTeamHiringRequirements(teamId: Principal | null): Promise<Array<HiringRequirement>>;
    getTeamProfile(teamId: Principal | null): Promise<TeamProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserTimeline(userId: Principal): Promise<Array<Post>>;
    initializeUser(email: string, name: string, avatar: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchAllHiringRequirementsForPlayers(filters: SystemHiringRequirementSearchFilters): Promise<Array<SystemHiringRequirement>>;
    searchTalent(filters: TalentSearchFilters): Promise<Array<UserProfile>>;
    setUserType(userType: UserType): Promise<void>;
    submitEndorsement(playerId: Principal, endorsementType: EndorsementType): Promise<EndorsementSummary>;
    submitFeedback(message: string): Promise<void>;
    updateReadinessRequirement(requirement: bigint): Promise<void>;
}
import type { Endorsement as _Endorsement, EndorsementType as _EndorsementType, ExternalBlob as _ExternalBlob, Game as _Game, HiringRequirement as _HiringRequirement, Level as _Level, Post as _Post, Role as _Role, SystemHiringRequirement as _SystemHiringRequirement, SystemHiringRequirementSearchFilters as _SystemHiringRequirementSearchFilters, TalentSearchFilters as _TalentSearchFilters, TeamProfile as _TeamProfile, User as _User, UserProfile as _UserProfile, UserRole as _UserRole, UserType as _UserType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createHiringRequirement(arg0: Game, arg1: Role, arg2: Level, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createHiringRequirement(to_candid_Game_n10(this._uploadFile, this._downloadFile, arg0), to_candid_Role_n12(this._uploadFile, this._downloadFile, arg1), to_candid_Level_n14(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHiringRequirement(to_candid_Game_n10(this._uploadFile, this._downloadFile, arg0), to_candid_Role_n12(this._uploadFile, this._downloadFile, arg1), to_candid_Level_n14(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async createOrUpdateProfile(arg0: UserType, arg1: Game, arg2: Role, arg3: Level, arg4: boolean, arg5: bigint, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(to_candid_UserType_n16(this._uploadFile, this._downloadFile, arg0), to_candid_Game_n10(this._uploadFile, this._downloadFile, arg1), to_candid_Role_n12(this._uploadFile, this._downloadFile, arg2), to_candid_Level_n14(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(to_candid_UserType_n16(this._uploadFile, this._downloadFile, arg0), to_candid_Game_n10(this._uploadFile, this._downloadFile, arg1), to_candid_Role_n12(this._uploadFile, this._downloadFile, arg2), to_candid_Level_n14(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async createOrUpdateTeamProfile(arg0: string, arg1: Array<Game>, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateTeamProfile(arg0, to_candid_vec_n18(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateTeamProfile(arg0, to_candid_vec_n18(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async createPost(arg0: string, arg1: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, await to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, await to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteEndorsement(arg0: bigint): Promise<EndorsementSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEndorsement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEndorsement(arg0);
            return result;
        }
    }
    async getAllEndorsements(): Promise<Array<Endorsement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEndorsements();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEndorsements();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFeedback(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeedback();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeedback();
            return result;
        }
    }
    async getAllHiringRequirements(): Promise<Array<HiringRequirement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHiringRequirements();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHiringRequirements();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUser(): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUser();
                return from_candid_User_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUser();
            return from_candid_User_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeed(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeed();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeed();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerEndorsementSummary(arg0: Principal): Promise<EndorsementSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerEndorsementSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerEndorsementSummary(arg0);
            return result;
        }
    }
    async getPlayerEndorsements(arg0: Principal): Promise<Array<Endorsement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerEndorsements(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerEndorsements(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReadinessMetrics(arg0: Principal | null): Promise<ReadinessMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getReadinessMetrics(to_candid_opt_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReadinessMetrics(to_candid_opt_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getTeamHiringRequirements(arg0: Principal | null): Promise<Array<HiringRequirement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamHiringRequirements(to_candid_opt_n50(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamHiringRequirements(to_candid_opt_n50(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamProfile(arg0: Principal | null): Promise<TeamProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamProfile(to_candid_opt_n50(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamProfile(to_candid_opt_n50(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTimeline(arg0: Principal): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTimeline(arg0);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTimeline(arg0);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeUser(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeUser(arg0, arg1, arg2);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n55(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n55(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchAllHiringRequirementsForPlayers(arg0: SystemHiringRequirementSearchFilters): Promise<Array<SystemHiringRequirement>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAllHiringRequirementsForPlayers(to_candid_SystemHiringRequirementSearchFilters_n57(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAllHiringRequirementsForPlayers(to_candid_SystemHiringRequirementSearchFilters_n57(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchTalent(arg0: TalentSearchFilters): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTalent(to_candid_TalentSearchFilters_n62(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTalent(to_candid_TalentSearchFilters_n62(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserType(arg0: UserType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserType(to_candid_UserType_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserType(to_candid_UserType_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitEndorsement(arg0: Principal, arg1: EndorsementType): Promise<EndorsementSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEndorsement(arg0, to_candid_EndorsementType_n65(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEndorsement(arg0, to_candid_EndorsementType_n65(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitFeedback(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0);
            return result;
        }
    }
    async updateReadinessRequirement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReadinessRequirement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReadinessRequirement(arg0);
            return result;
        }
    }
}
function from_candid_EndorsementType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EndorsementType): EndorsementType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Endorsement_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Endorsement): Endorsement {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Game_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Game): Game {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_HiringRequirement_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HiringRequirement): HiringRequirement {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Level_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Level): Level {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_Post_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Promise<Post> {
    return await from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_SystemHiringRequirement_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SystemHiringRequirement): SystemHiringRequirement {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
function from_candid_TeamProfile_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamProfile): TeamProfile {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserType): UserType {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_User_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserType]): UserType | null {
    return value.length === 0 ? null : from_candid_UserType_n38(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamProfile]): TeamProfile | null {
    return value.length === 0 ? null : from_candid_TeamProfile_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    playerId: Principal;
    createdAt: bigint;
    endorsementType: _EndorsementType;
    endorserId: Principal;
}): {
    id: bigint;
    playerId: Principal;
    createdAt: bigint;
    endorsementType: EndorsementType;
    endorserId: Principal;
} {
    return {
        id: value.id,
        playerId: value.playerId,
        createdAt: value.createdAt,
        endorsementType: from_candid_EndorsementType_n24(_uploadFile, _downloadFile, value.endorsementType),
        endorserId: value.endorserId
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    game: _Game;
    createdAt: bigint;
    role: _Role;
    minReadinessScore: bigint;
    skillLevel: _Level;
    teamId: Principal;
    requirements: string;
}): {
    id: bigint;
    game: Game;
    createdAt: bigint;
    role: Role;
    minReadinessScore: bigint;
    skillLevel: Level;
    teamId: Principal;
    requirements: string;
} {
    return {
        id: value.id,
        game: from_candid_Game_n29(_uploadFile, _downloadFile, value.game),
        createdAt: value.createdAt,
        role: from_candid_Role_n31(_uploadFile, _downloadFile, value.role),
        minReadinessScore: value.minReadinessScore,
        skillLevel: from_candid_Level_n33(_uploadFile, _downloadFile, value.skillLevel),
        teamId: value.teamId,
        requirements: value.requirements
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    userType: _UserType;
    username: string;
    game: _Game;
    role: _Role;
    level: _Level;
    readinessRequirement: bigint;
    globalReadinessScore: bigint;
    openToTeam: boolean;
}): {
    id: Principal;
    userType: UserType;
    username: string;
    game: Game;
    role: Role;
    level: Level;
    readinessRequirement: bigint;
    globalReadinessScore: bigint;
    openToTeam: boolean;
} {
    return {
        id: value.id,
        userType: from_candid_UserType_n38(_uploadFile, _downloadFile, value.userType),
        username: value.username,
        game: from_candid_Game_n29(_uploadFile, _downloadFile, value.game),
        role: from_candid_Role_n31(_uploadFile, _downloadFile, value.role),
        level: from_candid_Level_n33(_uploadFile, _downloadFile, value.level),
        readinessRequirement: value.readinessRequirement,
        globalReadinessScore: value.globalReadinessScore,
        openToTeam: value.openToTeam
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    userType: [] | [_UserType];
    name: string;
    email: string;
    avatar: string;
}): {
    id: Principal;
    userType?: UserType;
    name: string;
    email: string;
    avatar: string;
} {
    return {
        id: value.id,
        userType: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.userType)),
        name: value.name,
        email: value.email,
        avatar: value.avatar
    };
}
async function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    clip: [] | [_ExternalBlob];
    userId: Principal;
    improvementText: string;
    createdAt: bigint;
}): Promise<{
    id: bigint;
    clip?: ExternalBlob;
    userId: Principal;
    improvementText: string;
    createdAt: bigint;
}> {
    return {
        id: value.id,
        clip: record_opt_to_undefined(await from_candid_opt_n48(_uploadFile, _downloadFile, value.clip)),
        userId: value.userId,
        improvementText: value.improvementText,
        createdAt: value.createdAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    userType: _UserType;
    teamName: string;
    contactInfo: string;
    gamesRecruiting: Array<_Game>;
    description: string;
    requirements: string;
}): {
    id: Principal;
    userType: UserType;
    teamName: string;
    contactInfo: string;
    gamesRecruiting: Array<Game>;
    description: string;
    requirements: string;
} {
    return {
        id: value.id,
        userType: from_candid_UserType_n38(_uploadFile, _downloadFile, value.userType),
        teamName: value.teamName,
        contactInfo: value.contactInfo,
        gamesRecruiting: from_candid_vec_n54(_uploadFile, _downloadFile, value.gamesRecruiting),
        description: value.description,
        requirements: value.requirements
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    teamName: string;
    contactInfo: string;
    game: _Game;
    createdAt: bigint;
    role: _Role;
    minReadinessScore: bigint;
    skillLevel: _Level;
    teamId: Principal;
    requirements: string;
}): {
    id: bigint;
    teamName: string;
    contactInfo: string;
    game: Game;
    createdAt: bigint;
    role: Role;
    minReadinessScore: bigint;
    skillLevel: Level;
    teamId: Principal;
    requirements: string;
} {
    return {
        id: value.id,
        teamName: value.teamName,
        contactInfo: value.contactInfo,
        game: from_candid_Game_n29(_uploadFile, _downloadFile, value.game),
        createdAt: value.createdAt,
        role: from_candid_Role_n31(_uploadFile, _downloadFile, value.role),
        minReadinessScore: value.minReadinessScore,
        skillLevel: from_candid_Level_n33(_uploadFile, _downloadFile, value.skillLevel),
        teamId: value.teamId,
        requirements: value.requirements
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: string;
} | {
    punctual: null;
} | {
    scrimPartner: null;
} | {
    consistency: null;
} | {
    reliableComms: null;
}): {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "punctual";
    punctual: null;
} | {
    __kind__: "scrimPartner";
    scrimPartner: null;
} | {
    __kind__: "consistency";
    consistency: null;
} | {
    __kind__: "reliableComms";
    reliableComms: null;
} {
    return "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "punctual" in value ? {
        __kind__: "punctual",
        punctual: value.punctual
    } : "scrimPartner" in value ? {
        __kind__: "scrimPartner",
        scrimPartner: value.scrimPartner
    } : "consistency" in value ? {
        __kind__: "consistency",
        consistency: value.consistency
    } : "reliableComms" in value ? {
        __kind__: "reliableComms",
        reliableComms: value.reliableComms
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    freeFire: null;
} | {
    other: string;
} | {
    bgmi: null;
} | {
    codm: null;
}): {
    __kind__: "freeFire";
    freeFire: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "bgmi";
    bgmi: null;
} | {
    __kind__: "codm";
    codm: null;
} {
    return "freeFire" in value ? {
        __kind__: "freeFire",
        freeFire: value.freeFire
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "bgmi" in value ? {
        __kind__: "bgmi",
        bgmi: value.bgmi
    } : "codm" in value ? {
        __kind__: "codm",
        codm: value.codm
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    attacker: null;
} | {
    other: string;
} | {
    support: null;
} | {
    tank: null;
} | {
    sniper: null;
}): {
    __kind__: "attacker";
    attacker: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "support";
    support: null;
} | {
    __kind__: "tank";
    tank: null;
} | {
    __kind__: "sniper";
    sniper: null;
} {
    return "attacker" in value ? {
        __kind__: "attacker",
        attacker: value.attacker
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "support" in value ? {
        __kind__: "support",
        support: value.support
    } : "tank" in value ? {
        __kind__: "tank",
        tank: value.tank
    } : "sniper" in value ? {
        __kind__: "sniper",
        sniper: value.sniper
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    grinder: null;
} | {
    casual: null;
}): Level {
    return "grinder" in value ? Level.grinder : "casual" in value ? Level.casual : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    player: null;
} | {
    team: null;
}): UserType {
    return "player" in value ? UserType.player : "team" in value ? UserType.team : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Endorsement>): Array<Endorsement> {
    return value.map((x)=>from_candid_Endorsement_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HiringRequirement>): Array<HiringRequirement> {
    return value.map((x)=>from_candid_HiringRequirement_n27(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Promise<Array<Post>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Post_n46(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Game>): Array<Game> {
    return value.map((x)=>from_candid_Game_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SystemHiringRequirement>): Array<SystemHiringRequirement> {
    return value.map((x)=>from_candid_SystemHiringRequirement_n60(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n36(_uploadFile, _downloadFile, x));
}
function to_candid_EndorsementType_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EndorsementType): _EndorsementType {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Game_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Game): _Game {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Level_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Level): _Level {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_SystemHiringRequirementSearchFilters_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SystemHiringRequirementSearchFilters): _SystemHiringRequirementSearchFilters {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_TalentSearchFilters_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TalentSearchFilters): _TalentSearchFilters {
    return to_candid_record_n63(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserType): _UserType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    userType: UserType;
    username: string;
    game: Game;
    role: Role;
    level: Level;
    readinessRequirement: bigint;
    globalReadinessScore: bigint;
    openToTeam: boolean;
}): {
    id: Principal;
    userType: _UserType;
    username: string;
    game: _Game;
    role: _Role;
    level: _Level;
    readinessRequirement: bigint;
    globalReadinessScore: bigint;
    openToTeam: boolean;
} {
    return {
        id: value.id,
        userType: to_candid_UserType_n16(_uploadFile, _downloadFile, value.userType),
        username: value.username,
        game: to_candid_Game_n10(_uploadFile, _downloadFile, value.game),
        role: to_candid_Role_n12(_uploadFile, _downloadFile, value.role),
        level: to_candid_Level_n14(_uploadFile, _downloadFile, value.level),
        readinessRequirement: value.readinessRequirement,
        globalReadinessScore: value.globalReadinessScore,
        openToTeam: value.openToTeam
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    game?: Game;
    role?: Role;
    minReadinessScore?: bigint;
    returnedFields?: Array<string>;
    skillLevel?: Level;
    searchQuery?: string;
}): {
    game: [] | [_Game];
    role: [] | [_Role];
    minReadinessScore: [] | [bigint];
    returnedFields: [] | [Array<string>];
    skillLevel: [] | [_Level];
    searchQuery: [] | [string];
} {
    return {
        game: value.game ? candid_some(to_candid_Game_n10(_uploadFile, _downloadFile, value.game)) : candid_none(),
        role: value.role ? candid_some(to_candid_Role_n12(_uploadFile, _downloadFile, value.role)) : candid_none(),
        minReadinessScore: value.minReadinessScore ? candid_some(value.minReadinessScore) : candid_none(),
        returnedFields: value.returnedFields ? candid_some(value.returnedFields) : candid_none(),
        skillLevel: value.skillLevel ? candid_some(to_candid_Level_n14(_uploadFile, _downloadFile, value.skillLevel)) : candid_none(),
        searchQuery: value.searchQuery ? candid_some(value.searchQuery) : candid_none()
    };
}
function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasClipOnly: boolean;
    game?: Game;
    role?: Role;
    minReadinessScore?: bigint;
    level?: Level;
    openToTeamOnly: boolean;
    searchQuery?: string;
}): {
    hasClipOnly: boolean;
    game: [] | [_Game];
    role: [] | [_Role];
    minReadinessScore: [] | [bigint];
    level: [] | [_Level];
    openToTeamOnly: boolean;
    searchQuery: [] | [string];
} {
    return {
        hasClipOnly: value.hasClipOnly,
        game: value.game ? candid_some(to_candid_Game_n10(_uploadFile, _downloadFile, value.game)) : candid_none(),
        role: value.role ? candid_some(to_candid_Role_n12(_uploadFile, _downloadFile, value.role)) : candid_none(),
        minReadinessScore: value.minReadinessScore ? candid_some(value.minReadinessScore) : candid_none(),
        level: value.level ? candid_some(to_candid_Level_n14(_uploadFile, _downloadFile, value.level)) : candid_none(),
        openToTeamOnly: value.openToTeamOnly,
        searchQuery: value.searchQuery ? candid_some(value.searchQuery) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "freeFire";
    freeFire: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "bgmi";
    bgmi: null;
} | {
    __kind__: "codm";
    codm: null;
}): {
    freeFire: null;
} | {
    other: string;
} | {
    bgmi: null;
} | {
    codm: null;
} {
    return value.__kind__ === "freeFire" ? {
        freeFire: value.freeFire
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "bgmi" ? {
        bgmi: value.bgmi
    } : value.__kind__ === "codm" ? {
        codm: value.codm
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "attacker";
    attacker: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "support";
    support: null;
} | {
    __kind__: "tank";
    tank: null;
} | {
    __kind__: "sniper";
    sniper: null;
}): {
    attacker: null;
} | {
    other: string;
} | {
    support: null;
} | {
    tank: null;
} | {
    sniper: null;
} {
    return value.__kind__ === "attacker" ? {
        attacker: value.attacker
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "support" ? {
        support: value.support
    } : value.__kind__ === "tank" ? {
        tank: value.tank
    } : value.__kind__ === "sniper" ? {
        sniper: value.sniper
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Level): {
    grinder: null;
} | {
    casual: null;
} {
    return value == Level.grinder ? {
        grinder: null
    } : value == Level.casual ? {
        casual: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserType): {
    player: null;
} | {
    team: null;
} {
    return value == UserType.player ? {
        player: null
    } : value == UserType.team ? {
        team: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "punctual";
    punctual: null;
} | {
    __kind__: "scrimPartner";
    scrimPartner: null;
} | {
    __kind__: "consistency";
    consistency: null;
} | {
    __kind__: "reliableComms";
    reliableComms: null;
}): {
    custom: string;
} | {
    punctual: null;
} | {
    scrimPartner: null;
} | {
    consistency: null;
} | {
    reliableComms: null;
} {
    return value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "punctual" ? {
        punctual: value.punctual
    } : value.__kind__ === "scrimPartner" ? {
        scrimPartner: value.scrimPartner
    } : value.__kind__ === "consistency" ? {
        consistency: value.consistency
    } : value.__kind__ === "reliableComms" ? {
        reliableComms: value.reliableComms
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Game>): Array<_Game> {
    return value.map((x)=>to_candid_Game_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
